# Generated by Django 4.2 on 2023-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='No Description Provided(He/She is Gay)', null=True),
        ),
    ]
