# Generated by Django 4.2 on 2023-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile/unknown-profile-picture.png', null=True, upload_to='profile/'),
        ),
    ]
