# Generated by Django 4.2.3 on 2023-07-11 05:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
