# Generated by Django 4.1.7 on 2023-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0002_remove_answer_text_answer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='description',
            field=models.CharField(default='No Description Provided', max_length=100),
        ),
    ]
