# Generated by Django 4.1.7 on 2023-04-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0003_alter_code_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='short_description',
            field=models.CharField(default='No Description Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='No Description Provided', max_length=100),
        ),
    ]
