# Generated by Django 4.2 on 2023-06-17 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0004_answer_short_description_question_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='code',
            name='type',
            field=models.CharField(choices=[('TXT', 'TextFile'), ('PY', 'Python'), ('JS', 'Javascript'), ('TS', 'Typescript'), ('C', 'C'), ('CPP', 'C++'), ('CS', 'Csharp'), ('JV', 'Java')], default='TXT', max_length=3),
        ),
    ]
