# Generated by Django 4.2 on 2023-06-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0005_answer_created_at_code_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='code',
            name='score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AddField(
            model_name='code',
            name='short_description',
            field=models.CharField(default='No Description Provided', max_length=100),
        ),
    ]
