# Generated by Django 4.2 on 2023-06-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0006_remove_answer_score_remove_code_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='description',
        ),
    ]
