# Generated by Django 4.2 on 2023-06-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0007_remove_code_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='type',
            field=models.CharField(choices=[('TXT', 'TextFile'), ('PY', 'Python'), ('JS', 'Javascript'), ('C', 'C'), ('CPP', 'C++'), ('CS', 'Csharp'), ('JV', 'Java')], default='TXT', max_length=3),
        ),
    ]
