# Generated by Django 4.2 on 2023-06-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0008_alter_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='code',
        ),
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeisc.code'),
        ),
    ]
