# Generated by Django 4.2 on 2023-06-22 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeisc', '0009_remove_answer_code_answer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Code_Author', to=settings.AUTH_USER_MODEL),
        ),
    ]
