# Generated by Django 4.2 on 2023-06-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0013_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='code',
        ),
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.ManyToManyField(blank=True, to='codeisc.code'),
        ),
    ]
