# Generated by Django 4.2.3 on 2023-07-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeisc', '0016_code_tags_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
